export const specialCharacters: string = ",/\\!@#$%^&*()_+{}[]<=>?;':\"|";
export const upiServices: string[] = ["apl",
	"axl",
	"abfspay",
	"abfspay",
	"axisb",
	"idfcbank",
	"icici",
	"okaxis",
	"yesg",
	"jupiteraxis",
	"goaxb",
	"icici",
	"ikwik",
	"naviaxis",
	"NIYOICICI",
	"ybl",
	"pingpay",
	"shriramhdfcbank",
	"sliceaxis",
	"tapicici",
	"timecosmos",
	"yesbank",
	"idfcbank",
	"waicici",
	"icici",
	"zoicici"]